server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    git:
      enabled: true
spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/h2
  graphql:
    cors:
      allowed-origins:
        - http://localhost:5173
        - http://localhost:4173
        - http://localhost:4000
      allowed-methods: POST
    graphiql:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/
application:
  persistence:
    implementation: HIBERNATE
  host: http://localhost:${server.port}
logging:
  level:
    org:
      hibernate:
        SQL: debug
        stat: debug